global:
  scrape_interval: 10s
  scrape_timeout: 3s

scrape_configs:
  - job_name: "synapzeai-scrape"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["testsservice-api:8080", "userservice-api:8080", "paymentservice-api:8080"]