apiVersion: apps/v1
kind: Deployment
metadata:
  name: testsservice-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testsservice-api
  template:
    metadata:
      labels:
        app: testsservice-api
    spec:
      containers:
      - name: testsservice-api
        image: zhenya3148/synapzeai-testsservice-backend:1.0
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: testsservice-api-service
spec:
  selector:
    app: testsservice-api
  ports:
  - port: 8080
    targetPort: 8080