apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      
      - path: /api/Test
        pathType: Prefix
        backend:
          service:
            name: testsservice-api-service
            port:
              number: 8080
              
      - path: /api/Account
        pathType: Prefix
        backend:
          service:
            name: userservice-api-service
            port:
              number: 8080
              
      - path: /api/Payments
        pathType: Prefix
        backend:
          service:
            name: paymentservice-api-service
            port:
              number: 8080